// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdaltcvpncdfocktnokn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkYWx0Y3ZwbmNkZm9ja3Rub2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDIwOTgsImV4cCI6MjA2MzU3ODA5OH0.h61gcLd3J06ccu4lumZBH-kQCUsl0c8v9mu3pzrfdfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);